---
title: "Shoalmont Games Post 1"
date: 2018-09-03
---
author: max
email: max.vanderheyden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a place to post about games

# social links
twitter_username: maxpaulv
github_username:  maxmaxmax512

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
